using Domain.Entities;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Persistence.Extensions
{
    public static class SeedingTrietExamData
    {
        public static void Seeding(ModelBuilder modelBuilder)
        {

            modelBuilder.Entity<BankQuestion>().HasData(
            new BankQuestion { Id = 1, Content = "Câu 1: Chủ nghĩa duy vật biện chứng - Nội dung trọng tâm số 1", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 2, Content = "Câu 2: Chủ nghĩa duy vật biện chứng - Nội dung trọng tâm số 2", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 3, Content = "Câu 3: Chủ nghĩa duy vật biện chứng - Nội dung trọng tâm số 3", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 4, Content = "Câu 4: Chủ nghĩa duy vật biện chứng - Nội dung trọng tâm số 4", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 5, Content = "Câu 5: Chủ nghĩa duy vật biện chứng - Nội dung trọng tâm số 5", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 6, Content = "Câu 6: Chủ nghĩa duy vật biện chứng - Nội dung trọng tâm số 6", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 7, Content = "Câu 7: Chủ nghĩa duy vật biện chứng - Nội dung trọng tâm số 7", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 8, Content = "Câu 8: Chủ nghĩa duy vật biện chứng - Nội dung trọng tâm số 8", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 9, Content = "Câu 9: Chủ nghĩa duy vật biện chứng - Nội dung trọng tâm số 9", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 10, Content = "Câu 10: Phép biện chứng - Nội dung trọng tâm số 10", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 11, Content = "Câu 11: Phép biện chứng - Nội dung trọng tâm số 11", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 12, Content = "Câu 12: Phép biện chứng - Nội dung trọng tâm số 12", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 13, Content = "Câu 13: Phép biện chứng - Nội dung trọng tâm số 13", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 14, Content = "Câu 14: Phép biện chứng - Nội dung trọng tâm số 14", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 15, Content = "Câu 15: Phép biện chứng - Nội dung trọng tâm số 15", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 16, Content = "Câu 16: Phép biện chứng - Nội dung trọng tâm số 16", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 17, Content = "Câu 17: Phép biện chứng - Nội dung trọng tâm số 17", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 18, Content = "Câu 18: Phép biện chứng - Nội dung trọng tâm số 18", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 19, Content = "Câu 19: Vật chất và ý thức - Nội dung trọng tâm số 19", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 20, Content = "Câu 20: Vật chất và ý thức - Nội dung trọng tâm số 20", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 21, Content = "Câu 21: Vật chất và ý thức - Nội dung trọng tâm số 21", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 22, Content = "Câu 22: Vật chất và ý thức - Nội dung trọng tâm số 22", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 23, Content = "Câu 23: Vật chất và ý thức - Nội dung trọng tâm số 23", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 24, Content = "Câu 24: Vật chất và ý thức - Nội dung trọng tâm số 24", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 25, Content = "Câu 25: Vật chất và ý thức - Nội dung trọng tâm số 25", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 26, Content = "Câu 26: Vật chất và ý thức - Nội dung trọng tâm số 26", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 27, Content = "Câu 27: Vật chất và ý thức - Nội dung trọng tâm số 27", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 28, Content = "Câu 28: Phép biện chứng về lượng và chất - Nội dung trọng tâm số 28", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 29, Content = "Câu 29: Phép biện chứng về lượng và chất - Nội dung trọng tâm số 29", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 30, Content = "Câu 30: Phép biện chứng về lượng và chất - Nội dung trọng tâm số 30", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 31, Content = "Câu 31: Phép biện chứng về lượng và chất - Nội dung trọng tâm số 31", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 32, Content = "Câu 32: Phép biện chứng về lượng và chất - Nội dung trọng tâm số 32", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 33, Content = "Câu 33: Phép biện chứng về lượng và chất - Nội dung trọng tâm số 33", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 34, Content = "Câu 34: Phép biện chứng về lượng và chất - Nội dung trọng tâm số 34", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 35, Content = "Câu 35: Phép biện chứng về lượng và chất - Nội dung trọng tâm số 35", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 36, Content = "Câu 36: Phép biện chứng về lượng và chất - Nội dung trọng tâm số 36", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 37, Content = "Câu 37: Nguyên lý về mâu thuẫn - Nội dung trọng tâm số 37", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 38, Content = "Câu 38: Nguyên lý về mâu thuẫn - Nội dung trọng tâm số 38", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 39, Content = "Câu 39: Nguyên lý về mâu thuẫn - Nội dung trọng tâm số 39", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 40, Content = "Câu 40: Nguyên lý về mâu thuẫn - Nội dung trọng tâm số 40", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 41, Content = "Câu 41: Nguyên lý về mâu thuẫn - Nội dung trọng tâm số 41", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 42, Content = "Câu 42: Nguyên lý về mâu thuẫn - Nội dung trọng tâm số 42", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 43, Content = "Câu 43: Nguyên lý về mâu thuẫn - Nội dung trọng tâm số 43", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 44, Content = "Câu 44: Nguyên lý về mâu thuẫn - Nội dung trọng tâm số 44", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 45, Content = "Câu 45: Nguyên lý về mâu thuẫn - Nội dung trọng tâm số 45", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 46, Content = "Câu 46: Nhận thức và thực tiễn - Nội dung trọng tâm số 46", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 47, Content = "Câu 47: Nhận thức và thực tiễn - Nội dung trọng tâm số 47", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 48, Content = "Câu 48: Nhận thức và thực tiễn - Nội dung trọng tâm số 48", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 49, Content = "Câu 49: Nhận thức và thực tiễn - Nội dung trọng tâm số 49", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 50, Content = "Câu 50: Nhận thức và thực tiễn - Nội dung trọng tâm số 50", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 51, Content = "Câu 51: Nhận thức và thực tiễn - Nội dung trọng tâm số 1", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 52, Content = "Câu 52: Nhận thức và thực tiễn - Nội dung trọng tâm số 2", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 53, Content = "Câu 53: Nhận thức và thực tiễn - Nội dung trọng tâm số 3", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 54, Content = "Câu 54: Nhận thức và thực tiễn - Nội dung trọng tâm số 4", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 55, Content = "Câu 55: Vai trò của con người - Nội dung trọng tâm số 5", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 56, Content = "Câu 56: Vai trò của con người - Nội dung trọng tâm số 6", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 57, Content = "Câu 57: Vai trò của con người - Nội dung trọng tâm số 7", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 58, Content = "Câu 58: Vai trò của con người - Nội dung trọng tâm số 8", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 59, Content = "Câu 59: Vai trò của con người - Nội dung trọng tâm số 9", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 60, Content = "Câu 60: Vai trò của con người - Nội dung trọng tâm số 10", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 61, Content = "Câu 61: Vai trò của con người - Nội dung trọng tâm số 11", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 62, Content = "Câu 62: Vai trò của con người - Nội dung trọng tâm số 12", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 63, Content = "Câu 63: Vai trò của con người - Nội dung trọng tâm số 13", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 64, Content = "Câu 64: Chủ nghĩa duy vật lịch sử - Nội dung trọng tâm số 14", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 65, Content = "Câu 65: Chủ nghĩa duy vật lịch sử - Nội dung trọng tâm số 15", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 66, Content = "Câu 66: Chủ nghĩa duy vật lịch sử - Nội dung trọng tâm số 16", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 67, Content = "Câu 67: Chủ nghĩa duy vật lịch sử - Nội dung trọng tâm số 17", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 68, Content = "Câu 68: Chủ nghĩa duy vật lịch sử - Nội dung trọng tâm số 18", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 69, Content = "Câu 69: Chủ nghĩa duy vật lịch sử - Nội dung trọng tâm số 19", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 70, Content = "Câu 70: Chủ nghĩa duy vật lịch sử - Nội dung trọng tâm số 20", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 71, Content = "Câu 71: Chủ nghĩa duy vật lịch sử - Nội dung trọng tâm số 21", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 72, Content = "Câu 72: Chủ nghĩa duy vật lịch sử - Nội dung trọng tâm số 22", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 73, Content = "Câu 73: Hình thái kinh tế xã hội - Nội dung trọng tâm số 23", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 74, Content = "Câu 74: Hình thái kinh tế xã hội - Nội dung trọng tâm số 24", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 75, Content = "Câu 75: Hình thái kinh tế xã hội - Nội dung trọng tâm số 25", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 76, Content = "Câu 76: Hình thái kinh tế xã hội - Nội dung trọng tâm số 26", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 77, Content = "Câu 77: Hình thái kinh tế xã hội - Nội dung trọng tâm số 27", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 78, Content = "Câu 78: Hình thái kinh tế xã hội - Nội dung trọng tâm số 28", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 79, Content = "Câu 79: Hình thái kinh tế xã hội - Nội dung trọng tâm số 29", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 80, Content = "Câu 80: Hình thái kinh tế xã hội - Nội dung trọng tâm số 30", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 81, Content = "Câu 81: Hình thái kinh tế xã hội - Nội dung trọng tâm số 31", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 82, Content = "Câu 82: Giai cấp và đấu tranh giai cấp - Nội dung trọng tâm số 32", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 83, Content = "Câu 83: Giai cấp và đấu tranh giai cấp - Nội dung trọng tâm số 33", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 84, Content = "Câu 84: Giai cấp và đấu tranh giai cấp - Nội dung trọng tâm số 34", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 85, Content = "Câu 85: Giai cấp và đấu tranh giai cấp - Nội dung trọng tâm số 35", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 86, Content = "Câu 86: Giai cấp và đấu tranh giai cấp - Nội dung trọng tâm số 36", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 87, Content = "Câu 87: Giai cấp và đấu tranh giai cấp - Nội dung trọng tâm số 37", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 88, Content = "Câu 88: Giai cấp và đấu tranh giai cấp - Nội dung trọng tâm số 38", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 89, Content = "Câu 89: Giai cấp và đấu tranh giai cấp - Nội dung trọng tâm số 39", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 90, Content = "Câu 90: Giai cấp và đấu tranh giai cấp - Nội dung trọng tâm số 40", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 91, Content = "Câu 91: Nhà nước và cách mạng - Nội dung trọng tâm số 41", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 92, Content = "Câu 92: Nhà nước và cách mạng - Nội dung trọng tâm số 42", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 93, Content = "Câu 93: Nhà nước và cách mạng - Nội dung trọng tâm số 43", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 94, Content = "Câu 94: Nhà nước và cách mạng - Nội dung trọng tâm số 44", QuestionTypeId = 1, LevelId = 3, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 95, Content = "Câu 95: Nhà nước và cách mạng - Nội dung trọng tâm số 45", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 96, Content = "Câu 96: Nhà nước và cách mạng - Nội dung trọng tâm số 46", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 97, Content = "Câu 97: Nhà nước và cách mạng - Nội dung trọng tâm số 47", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 98, Content = "Câu 98: Nhà nước và cách mạng - Nội dung trọng tâm số 48", QuestionTypeId = 1, LevelId = 1, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 99, Content = "Câu 99: Nhà nước và cách mạng - Nội dung trọng tâm số 49", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null },
            new BankQuestion { Id = 100, Content = "Câu 100: Chủ nghĩa xã hội khoa học - Nội dung trọng tâm số 50", QuestionTypeId = 1, LevelId = 2, IsPublic = true, PremiumUserId = null }
            );

            modelBuilder.Entity<Answer>().HasData(
            new Answer { Id = 1, BankQuestionId = 1, AnswerText = "Đáp án 1 cho câu 1", IsCorrected = true },
            new Answer { Id = 2, BankQuestionId = 1, AnswerText = "Đáp án 2 cho câu 1", IsCorrected = false },
            new Answer { Id = 3, BankQuestionId = 1, AnswerText = "Đáp án 3 cho câu 1", IsCorrected = false },
            new Answer { Id = 4, BankQuestionId = 1, AnswerText = "Đáp án 4 cho câu 1", IsCorrected = false },
            new Answer { Id = 5, BankQuestionId = 2, AnswerText = "Đáp án 1 cho câu 2", IsCorrected = true },
            new Answer { Id = 6, BankQuestionId = 2, AnswerText = "Đáp án 2 cho câu 2", IsCorrected = false },
            new Answer { Id = 7, BankQuestionId = 2, AnswerText = "Đáp án 3 cho câu 2", IsCorrected = false },
            new Answer { Id = 8, BankQuestionId = 2, AnswerText = "Đáp án 4 cho câu 2", IsCorrected = false },
            new Answer { Id = 9, BankQuestionId = 3, AnswerText = "Đáp án 1 cho câu 3", IsCorrected = true },
            new Answer { Id = 10, BankQuestionId = 3, AnswerText = "Đáp án 2 cho câu 3", IsCorrected = false },
            new Answer { Id = 11, BankQuestionId = 3, AnswerText = "Đáp án 3 cho câu 3", IsCorrected = false },
            new Answer { Id = 12, BankQuestionId = 3, AnswerText = "Đáp án 4 cho câu 3", IsCorrected = false },
            new Answer { Id = 13, BankQuestionId = 4, AnswerText = "Đáp án 1 cho câu 4", IsCorrected = true },
            new Answer { Id = 14, BankQuestionId = 4, AnswerText = "Đáp án 2 cho câu 4", IsCorrected = false },
            new Answer { Id = 15, BankQuestionId = 4, AnswerText = "Đáp án 3 cho câu 4", IsCorrected = false },
            new Answer { Id = 16, BankQuestionId = 4, AnswerText = "Đáp án 4 cho câu 4", IsCorrected = false },
            new Answer { Id = 17, BankQuestionId = 5, AnswerText = "Đáp án 1 cho câu 5", IsCorrected = true },
            new Answer { Id = 18, BankQuestionId = 5, AnswerText = "Đáp án 2 cho câu 5", IsCorrected = false },
            new Answer { Id = 19, BankQuestionId = 5, AnswerText = "Đáp án 3 cho câu 5", IsCorrected = false },
            new Answer { Id = 20, BankQuestionId = 5, AnswerText = "Đáp án 4 cho câu 5", IsCorrected = false },
            new Answer { Id = 21, BankQuestionId = 6, AnswerText = "Đáp án 1 cho câu 6", IsCorrected = true },
            new Answer { Id = 22, BankQuestionId = 6, AnswerText = "Đáp án 2 cho câu 6", IsCorrected = false },
            new Answer { Id = 23, BankQuestionId = 6, AnswerText = "Đáp án 3 cho câu 6", IsCorrected = false },
            new Answer { Id = 24, BankQuestionId = 6, AnswerText = "Đáp án 4 cho câu 6", IsCorrected = false },
            new Answer { Id = 25, BankQuestionId = 7, AnswerText = "Đáp án 1 cho câu 7", IsCorrected = true },
            new Answer { Id = 26, BankQuestionId = 7, AnswerText = "Đáp án 2 cho câu 7", IsCorrected = false },
            new Answer { Id = 27, BankQuestionId = 7, AnswerText = "Đáp án 3 cho câu 7", IsCorrected = false },
            new Answer { Id = 28, BankQuestionId = 7, AnswerText = "Đáp án 4 cho câu 7", IsCorrected = false },
            new Answer { Id = 29, BankQuestionId = 8, AnswerText = "Đáp án 1 cho câu 8", IsCorrected = true },
            new Answer { Id = 30, BankQuestionId = 8, AnswerText = "Đáp án 2 cho câu 8", IsCorrected = false },
            new Answer { Id = 31, BankQuestionId = 8, AnswerText = "Đáp án 3 cho câu 8", IsCorrected = false },
            new Answer { Id = 32, BankQuestionId = 8, AnswerText = "Đáp án 4 cho câu 8", IsCorrected = false },
            new Answer { Id = 33, BankQuestionId = 9, AnswerText = "Đáp án 1 cho câu 9", IsCorrected = true },
            new Answer { Id = 34, BankQuestionId = 9, AnswerText = "Đáp án 2 cho câu 9", IsCorrected = false },
            new Answer { Id = 35, BankQuestionId = 9, AnswerText = "Đáp án 3 cho câu 9", IsCorrected = false },
            new Answer { Id = 36, BankQuestionId = 9, AnswerText = "Đáp án 4 cho câu 9", IsCorrected = false },
            new Answer { Id = 37, BankQuestionId = 10, AnswerText = "Đáp án 1 cho câu 10", IsCorrected = true },
            new Answer { Id = 38, BankQuestionId = 10, AnswerText = "Đáp án 2 cho câu 10", IsCorrected = false },
            new Answer { Id = 39, BankQuestionId = 10, AnswerText = "Đáp án 3 cho câu 10", IsCorrected = false },
            new Answer { Id = 40, BankQuestionId = 10, AnswerText = "Đáp án 4 cho câu 10", IsCorrected = false },
            new Answer { Id = 41, BankQuestionId = 11, AnswerText = "Đáp án 1 cho câu 11", IsCorrected = true },
            new Answer { Id = 42, BankQuestionId = 11, AnswerText = "Đáp án 2 cho câu 11", IsCorrected = false },
            new Answer { Id = 43, BankQuestionId = 11, AnswerText = "Đáp án 3 cho câu 11", IsCorrected = false },
            new Answer { Id = 44, BankQuestionId = 11, AnswerText = "Đáp án 4 cho câu 11", IsCorrected = false },
            new Answer { Id = 45, BankQuestionId = 12, AnswerText = "Đáp án 1 cho câu 12", IsCorrected = true },
            new Answer { Id = 46, BankQuestionId = 12, AnswerText = "Đáp án 2 cho câu 12", IsCorrected = false },
            new Answer { Id = 47, BankQuestionId = 12, AnswerText = "Đáp án 3 cho câu 12", IsCorrected = false },
            new Answer { Id = 48, BankQuestionId = 12, AnswerText = "Đáp án 4 cho câu 12", IsCorrected = false },
            new Answer { Id = 49, BankQuestionId = 13, AnswerText = "Đáp án 1 cho câu 13", IsCorrected = true },
            new Answer { Id = 50, BankQuestionId = 13, AnswerText = "Đáp án 2 cho câu 13", IsCorrected = false },
            new Answer { Id = 51, BankQuestionId = 13, AnswerText = "Đáp án 3 cho câu 13", IsCorrected = false },
            new Answer { Id = 52, BankQuestionId = 13, AnswerText = "Đáp án 4 cho câu 13", IsCorrected = false },
            new Answer { Id = 53, BankQuestionId = 14, AnswerText = "Đáp án 1 cho câu 14", IsCorrected = true },
            new Answer { Id = 54, BankQuestionId = 14, AnswerText = "Đáp án 2 cho câu 14", IsCorrected = false },
            new Answer { Id = 55, BankQuestionId = 14, AnswerText = "Đáp án 3 cho câu 14", IsCorrected = false },
            new Answer { Id = 56, BankQuestionId = 14, AnswerText = "Đáp án 4 cho câu 14", IsCorrected = false },
            new Answer { Id = 57, BankQuestionId = 15, AnswerText = "Đáp án 1 cho câu 15", IsCorrected = true },
            new Answer { Id = 58, BankQuestionId = 15, AnswerText = "Đáp án 2 cho câu 15", IsCorrected = false },
            new Answer { Id = 59, BankQuestionId = 15, AnswerText = "Đáp án 3 cho câu 15", IsCorrected = false },
            new Answer { Id = 60, BankQuestionId = 15, AnswerText = "Đáp án 4 cho câu 15", IsCorrected = false },
            new Answer { Id = 61, BankQuestionId = 16, AnswerText = "Đáp án 1 cho câu 16", IsCorrected = true },
            new Answer { Id = 62, BankQuestionId = 16, AnswerText = "Đáp án 2 cho câu 16", IsCorrected = false },
            new Answer { Id = 63, BankQuestionId = 16, AnswerText = "Đáp án 3 cho câu 16", IsCorrected = false },
            new Answer { Id = 64, BankQuestionId = 16, AnswerText = "Đáp án 4 cho câu 16", IsCorrected = false },
            new Answer { Id = 65, BankQuestionId = 17, AnswerText = "Đáp án 1 cho câu 17", IsCorrected = true },
            new Answer { Id = 66, BankQuestionId = 17, AnswerText = "Đáp án 2 cho câu 17", IsCorrected = false },
            new Answer { Id = 67, BankQuestionId = 17, AnswerText = "Đáp án 3 cho câu 17", IsCorrected = false },
            new Answer { Id = 68, BankQuestionId = 17, AnswerText = "Đáp án 4 cho câu 17", IsCorrected = false },
            new Answer { Id = 69, BankQuestionId = 18, AnswerText = "Đáp án 1 cho câu 18", IsCorrected = true },
            new Answer { Id = 70, BankQuestionId = 18, AnswerText = "Đáp án 2 cho câu 18", IsCorrected = false },
            new Answer { Id = 71, BankQuestionId = 18, AnswerText = "Đáp án 3 cho câu 18", IsCorrected = false },
            new Answer { Id = 72, BankQuestionId = 18, AnswerText = "Đáp án 4 cho câu 18", IsCorrected = false },
            new Answer { Id = 73, BankQuestionId = 19, AnswerText = "Đáp án 1 cho câu 19", IsCorrected = true },
            new Answer { Id = 74, BankQuestionId = 19, AnswerText = "Đáp án 2 cho câu 19", IsCorrected = false },
            new Answer { Id = 75, BankQuestionId = 19, AnswerText = "Đáp án 3 cho câu 19", IsCorrected = false },
            new Answer { Id = 76, BankQuestionId = 19, AnswerText = "Đáp án 4 cho câu 19", IsCorrected = false },
            new Answer { Id = 77, BankQuestionId = 20, AnswerText = "Đáp án 1 cho câu 20", IsCorrected = true },
            new Answer { Id = 78, BankQuestionId = 20, AnswerText = "Đáp án 2 cho câu 20", IsCorrected = false },
            new Answer { Id = 79, BankQuestionId = 20, AnswerText = "Đáp án 3 cho câu 20", IsCorrected = false },
            new Answer { Id = 80, BankQuestionId = 20, AnswerText = "Đáp án 4 cho câu 20", IsCorrected = false },
            new Answer { Id = 81, BankQuestionId = 21, AnswerText = "Đáp án 1 cho câu 21", IsCorrected = true },
            new Answer { Id = 82, BankQuestionId = 21, AnswerText = "Đáp án 2 cho câu 21", IsCorrected = false },
            new Answer { Id = 83, BankQuestionId = 21, AnswerText = "Đáp án 3 cho câu 21", IsCorrected = false },
            new Answer { Id = 84, BankQuestionId = 21, AnswerText = "Đáp án 4 cho câu 21", IsCorrected = false },
            new Answer { Id = 85, BankQuestionId = 22, AnswerText = "Đáp án 1 cho câu 22", IsCorrected = true },
            new Answer { Id = 86, BankQuestionId = 22, AnswerText = "Đáp án 2 cho câu 22", IsCorrected = false },
            new Answer { Id = 87, BankQuestionId = 22, AnswerText = "Đáp án 3 cho câu 22", IsCorrected = false },
            new Answer { Id = 88, BankQuestionId = 22, AnswerText = "Đáp án 4 cho câu 22", IsCorrected = false },
            new Answer { Id = 89, BankQuestionId = 23, AnswerText = "Đáp án 1 cho câu 23", IsCorrected = true },
            new Answer { Id = 90, BankQuestionId = 23, AnswerText = "Đáp án 2 cho câu 23", IsCorrected = false },
            new Answer { Id = 91, BankQuestionId = 23, AnswerText = "Đáp án 3 cho câu 23", IsCorrected = false },
            new Answer { Id = 92, BankQuestionId = 23, AnswerText = "Đáp án 4 cho câu 23", IsCorrected = false },
            new Answer { Id = 93, BankQuestionId = 24, AnswerText = "Đáp án 1 cho câu 24", IsCorrected = true },
            new Answer { Id = 94, BankQuestionId = 24, AnswerText = "Đáp án 2 cho câu 24", IsCorrected = false },
            new Answer { Id = 95, BankQuestionId = 24, AnswerText = "Đáp án 3 cho câu 24", IsCorrected = false },
            new Answer { Id = 96, BankQuestionId = 24, AnswerText = "Đáp án 4 cho câu 24", IsCorrected = false },
            new Answer { Id = 97, BankQuestionId = 25, AnswerText = "Đáp án 1 cho câu 25", IsCorrected = true },
            new Answer { Id = 98, BankQuestionId = 25, AnswerText = "Đáp án 2 cho câu 25", IsCorrected = false },
            new Answer { Id = 99, BankQuestionId = 25, AnswerText = "Đáp án 3 cho câu 25", IsCorrected = false },
            new Answer { Id = 100, BankQuestionId = 25, AnswerText = "Đáp án 4 cho câu 25", IsCorrected = false },
            new Answer { Id = 101, BankQuestionId = 26, AnswerText = "Đáp án 1 cho câu 26", IsCorrected = true },
            new Answer { Id = 102, BankQuestionId = 26, AnswerText = "Đáp án 2 cho câu 26", IsCorrected = false },
            new Answer { Id = 103, BankQuestionId = 26, AnswerText = "Đáp án 3 cho câu 26", IsCorrected = false },
            new Answer { Id = 104, BankQuestionId = 26, AnswerText = "Đáp án 4 cho câu 26", IsCorrected = false },
            new Answer { Id = 105, BankQuestionId = 27, AnswerText = "Đáp án 1 cho câu 27", IsCorrected = true },
            new Answer { Id = 106, BankQuestionId = 27, AnswerText = "Đáp án 2 cho câu 27", IsCorrected = false },
            new Answer { Id = 107, BankQuestionId = 27, AnswerText = "Đáp án 3 cho câu 27", IsCorrected = false },
            new Answer { Id = 108, BankQuestionId = 27, AnswerText = "Đáp án 4 cho câu 27", IsCorrected = false },
            new Answer { Id = 109, BankQuestionId = 28, AnswerText = "Đáp án 1 cho câu 28", IsCorrected = true },
            new Answer { Id = 110, BankQuestionId = 28, AnswerText = "Đáp án 2 cho câu 28", IsCorrected = false },
            new Answer { Id = 111, BankQuestionId = 28, AnswerText = "Đáp án 3 cho câu 28", IsCorrected = false },
            new Answer { Id = 112, BankQuestionId = 28, AnswerText = "Đáp án 4 cho câu 28", IsCorrected = false },
            new Answer { Id = 113, BankQuestionId = 29, AnswerText = "Đáp án 1 cho câu 29", IsCorrected = true },
            new Answer { Id = 114, BankQuestionId = 29, AnswerText = "Đáp án 2 cho câu 29", IsCorrected = false },
            new Answer { Id = 115, BankQuestionId = 29, AnswerText = "Đáp án 3 cho câu 29", IsCorrected = false },
            new Answer { Id = 116, BankQuestionId = 29, AnswerText = "Đáp án 4 cho câu 29", IsCorrected = false },
            new Answer { Id = 117, BankQuestionId = 30, AnswerText = "Đáp án 1 cho câu 30", IsCorrected = true },
            new Answer { Id = 118, BankQuestionId = 30, AnswerText = "Đáp án 2 cho câu 30", IsCorrected = false },
            new Answer { Id = 119, BankQuestionId = 30, AnswerText = "Đáp án 3 cho câu 30", IsCorrected = false },
            new Answer { Id = 120, BankQuestionId = 30, AnswerText = "Đáp án 4 cho câu 30", IsCorrected = false },
            new Answer { Id = 121, BankQuestionId = 31, AnswerText = "Đáp án 1 cho câu 31", IsCorrected = true },
            new Answer { Id = 122, BankQuestionId = 31, AnswerText = "Đáp án 2 cho câu 31", IsCorrected = false },
            new Answer { Id = 123, BankQuestionId = 31, AnswerText = "Đáp án 3 cho câu 31", IsCorrected = false },
            new Answer { Id = 124, BankQuestionId = 31, AnswerText = "Đáp án 4 cho câu 31", IsCorrected = false },
            new Answer { Id = 125, BankQuestionId = 32, AnswerText = "Đáp án 1 cho câu 32", IsCorrected = true },
            new Answer { Id = 126, BankQuestionId = 32, AnswerText = "Đáp án 2 cho câu 32", IsCorrected = false },
            new Answer { Id = 127, BankQuestionId = 32, AnswerText = "Đáp án 3 cho câu 32", IsCorrected = false },
            new Answer { Id = 128, BankQuestionId = 32, AnswerText = "Đáp án 4 cho câu 32", IsCorrected = false },
            new Answer { Id = 129, BankQuestionId = 33, AnswerText = "Đáp án 1 cho câu 33", IsCorrected = true },
            new Answer { Id = 130, BankQuestionId = 33, AnswerText = "Đáp án 2 cho câu 33", IsCorrected = false },
            new Answer { Id = 131, BankQuestionId = 33, AnswerText = "Đáp án 3 cho câu 33", IsCorrected = false },
            new Answer { Id = 132, BankQuestionId = 33, AnswerText = "Đáp án 4 cho câu 33", IsCorrected = false },
            new Answer { Id = 133, BankQuestionId = 34, AnswerText = "Đáp án 1 cho câu 34", IsCorrected = true },
            new Answer { Id = 134, BankQuestionId = 34, AnswerText = "Đáp án 2 cho câu 34", IsCorrected = false },
            new Answer { Id = 135, BankQuestionId = 34, AnswerText = "Đáp án 3 cho câu 34", IsCorrected = false },
            new Answer { Id = 136, BankQuestionId = 34, AnswerText = "Đáp án 4 cho câu 34", IsCorrected = false },
            new Answer { Id = 137, BankQuestionId = 35, AnswerText = "Đáp án 1 cho câu 35", IsCorrected = true },
            new Answer { Id = 138, BankQuestionId = 35, AnswerText = "Đáp án 2 cho câu 35", IsCorrected = false },
            new Answer { Id = 139, BankQuestionId = 35, AnswerText = "Đáp án 3 cho câu 35", IsCorrected = false },
            new Answer { Id = 140, BankQuestionId = 35, AnswerText = "Đáp án 4 cho câu 35", IsCorrected = false },
            new Answer { Id = 141, BankQuestionId = 36, AnswerText = "Đáp án 1 cho câu 36", IsCorrected = true },
            new Answer { Id = 142, BankQuestionId = 36, AnswerText = "Đáp án 2 cho câu 36", IsCorrected = false },
            new Answer { Id = 143, BankQuestionId = 36, AnswerText = "Đáp án 3 cho câu 36", IsCorrected = false },
            new Answer { Id = 144, BankQuestionId = 36, AnswerText = "Đáp án 4 cho câu 36", IsCorrected = false },
            new Answer { Id = 145, BankQuestionId = 37, AnswerText = "Đáp án 1 cho câu 37", IsCorrected = true },
            new Answer { Id = 146, BankQuestionId = 37, AnswerText = "Đáp án 2 cho câu 37", IsCorrected = false },
            new Answer { Id = 147, BankQuestionId = 37, AnswerText = "Đáp án 3 cho câu 37", IsCorrected = false },
            new Answer { Id = 148, BankQuestionId = 37, AnswerText = "Đáp án 4 cho câu 37", IsCorrected = false },
            new Answer { Id = 149, BankQuestionId = 38, AnswerText = "Đáp án 1 cho câu 38", IsCorrected = true },
            new Answer { Id = 150, BankQuestionId = 38, AnswerText = "Đáp án 2 cho câu 38", IsCorrected = false },
            new Answer { Id = 151, BankQuestionId = 38, AnswerText = "Đáp án 3 cho câu 38", IsCorrected = false },
            new Answer { Id = 152, BankQuestionId = 38, AnswerText = "Đáp án 4 cho câu 38", IsCorrected = false },
            new Answer { Id = 153, BankQuestionId = 39, AnswerText = "Đáp án 1 cho câu 39", IsCorrected = true },
            new Answer { Id = 154, BankQuestionId = 39, AnswerText = "Đáp án 2 cho câu 39", IsCorrected = false },
            new Answer { Id = 155, BankQuestionId = 39, AnswerText = "Đáp án 3 cho câu 39", IsCorrected = false },
            new Answer { Id = 156, BankQuestionId = 39, AnswerText = "Đáp án 4 cho câu 39", IsCorrected = false },
            new Answer { Id = 157, BankQuestionId = 40, AnswerText = "Đáp án 1 cho câu 40", IsCorrected = true },
            new Answer { Id = 158, BankQuestionId = 40, AnswerText = "Đáp án 2 cho câu 40", IsCorrected = false },
            new Answer { Id = 159, BankQuestionId = 40, AnswerText = "Đáp án 3 cho câu 40", IsCorrected = false },
            new Answer { Id = 160, BankQuestionId = 40, AnswerText = "Đáp án 4 cho câu 40", IsCorrected = false },
            new Answer { Id = 161, BankQuestionId = 41, AnswerText = "Đáp án 1 cho câu 41", IsCorrected = true },
            new Answer { Id = 162, BankQuestionId = 41, AnswerText = "Đáp án 2 cho câu 41", IsCorrected = false },
            new Answer { Id = 163, BankQuestionId = 41, AnswerText = "Đáp án 3 cho câu 41", IsCorrected = false },
            new Answer { Id = 164, BankQuestionId = 41, AnswerText = "Đáp án 4 cho câu 41", IsCorrected = false },
            new Answer { Id = 165, BankQuestionId = 42, AnswerText = "Đáp án 1 cho câu 42", IsCorrected = true },
            new Answer { Id = 166, BankQuestionId = 42, AnswerText = "Đáp án 2 cho câu 42", IsCorrected = false },
            new Answer { Id = 167, BankQuestionId = 42, AnswerText = "Đáp án 3 cho câu 42", IsCorrected = false },
            new Answer { Id = 168, BankQuestionId = 42, AnswerText = "Đáp án 4 cho câu 42", IsCorrected = false },
            new Answer { Id = 169, BankQuestionId = 43, AnswerText = "Đáp án 1 cho câu 43", IsCorrected = true },
            new Answer { Id = 170, BankQuestionId = 43, AnswerText = "Đáp án 2 cho câu 43", IsCorrected = false },
            new Answer { Id = 171, BankQuestionId = 43, AnswerText = "Đáp án 3 cho câu 43", IsCorrected = false },
            new Answer { Id = 172, BankQuestionId = 43, AnswerText = "Đáp án 4 cho câu 43", IsCorrected = false },
            new Answer { Id = 173, BankQuestionId = 44, AnswerText = "Đáp án 1 cho câu 44", IsCorrected = true },
            new Answer { Id = 174, BankQuestionId = 44, AnswerText = "Đáp án 2 cho câu 44", IsCorrected = false },
            new Answer { Id = 175, BankQuestionId = 44, AnswerText = "Đáp án 3 cho câu 44", IsCorrected = false },
            new Answer { Id = 176, BankQuestionId = 44, AnswerText = "Đáp án 4 cho câu 44", IsCorrected = false },
            new Answer { Id = 177, BankQuestionId = 45, AnswerText = "Đáp án 1 cho câu 45", IsCorrected = true },
            new Answer { Id = 178, BankQuestionId = 45, AnswerText = "Đáp án 2 cho câu 45", IsCorrected = false },
            new Answer { Id = 179, BankQuestionId = 45, AnswerText = "Đáp án 3 cho câu 45", IsCorrected = false },
            new Answer { Id = 180, BankQuestionId = 45, AnswerText = "Đáp án 4 cho câu 45", IsCorrected = false },
            new Answer { Id = 181, BankQuestionId = 46, AnswerText = "Đáp án 1 cho câu 46", IsCorrected = true },
            new Answer { Id = 182, BankQuestionId = 46, AnswerText = "Đáp án 2 cho câu 46", IsCorrected = false },
            new Answer { Id = 183, BankQuestionId = 46, AnswerText = "Đáp án 3 cho câu 46", IsCorrected = false },
            new Answer { Id = 184, BankQuestionId = 46, AnswerText = "Đáp án 4 cho câu 46", IsCorrected = false },
            new Answer { Id = 185, BankQuestionId = 47, AnswerText = "Đáp án 1 cho câu 47", IsCorrected = true },
            new Answer { Id = 186, BankQuestionId = 47, AnswerText = "Đáp án 2 cho câu 47", IsCorrected = false },
            new Answer { Id = 187, BankQuestionId = 47, AnswerText = "Đáp án 3 cho câu 47", IsCorrected = false },
            new Answer { Id = 188, BankQuestionId = 47, AnswerText = "Đáp án 4 cho câu 47", IsCorrected = false },
            new Answer { Id = 189, BankQuestionId = 48, AnswerText = "Đáp án 1 cho câu 48", IsCorrected = true },
            new Answer { Id = 190, BankQuestionId = 48, AnswerText = "Đáp án 2 cho câu 48", IsCorrected = false },
            new Answer { Id = 191, BankQuestionId = 48, AnswerText = "Đáp án 3 cho câu 48", IsCorrected = false },
            new Answer { Id = 192, BankQuestionId = 48, AnswerText = "Đáp án 4 cho câu 48", IsCorrected = false },
            new Answer { Id = 193, BankQuestionId = 49, AnswerText = "Đáp án 1 cho câu 49", IsCorrected = true },
            new Answer { Id = 194, BankQuestionId = 49, AnswerText = "Đáp án 2 cho câu 49", IsCorrected = false },
            new Answer { Id = 195, BankQuestionId = 49, AnswerText = "Đáp án 3 cho câu 49", IsCorrected = false },
            new Answer { Id = 196, BankQuestionId = 49, AnswerText = "Đáp án 4 cho câu 49", IsCorrected = false },
            new Answer { Id = 197, BankQuestionId = 50, AnswerText = "Đáp án 1 cho câu 50", IsCorrected = true },
            new Answer { Id = 198, BankQuestionId = 50, AnswerText = "Đáp án 2 cho câu 50", IsCorrected = false },
            new Answer { Id = 199, BankQuestionId = 50, AnswerText = "Đáp án 3 cho câu 50", IsCorrected = false },
            new Answer { Id = 200, BankQuestionId = 50, AnswerText = "Đáp án 4 cho câu 50", IsCorrected = false },
            new Answer { Id = 201, BankQuestionId = 51, AnswerText = "Đáp án 1 cho câu 51", IsCorrected = true },
            new Answer { Id = 202, BankQuestionId = 51, AnswerText = "Đáp án 2 cho câu 51", IsCorrected = false },
            new Answer { Id = 203, BankQuestionId = 51, AnswerText = "Đáp án 3 cho câu 51", IsCorrected = false },
            new Answer { Id = 204, BankQuestionId = 51, AnswerText = "Đáp án 4 cho câu 51", IsCorrected = false },
            new Answer { Id = 205, BankQuestionId = 52, AnswerText = "Đáp án 1 cho câu 52", IsCorrected = true },
            new Answer { Id = 206, BankQuestionId = 52, AnswerText = "Đáp án 2 cho câu 52", IsCorrected = false },
            new Answer { Id = 207, BankQuestionId = 52, AnswerText = "Đáp án 3 cho câu 52", IsCorrected = false },
            new Answer { Id = 208, BankQuestionId = 52, AnswerText = "Đáp án 4 cho câu 52", IsCorrected = false },
            new Answer { Id = 209, BankQuestionId = 53, AnswerText = "Đáp án 1 cho câu 53", IsCorrected = true },
            new Answer { Id = 210, BankQuestionId = 53, AnswerText = "Đáp án 2 cho câu 53", IsCorrected = false },
            new Answer { Id = 211, BankQuestionId = 53, AnswerText = "Đáp án 3 cho câu 53", IsCorrected = false },
            new Answer { Id = 212, BankQuestionId = 53, AnswerText = "Đáp án 4 cho câu 53", IsCorrected = false },
            new Answer { Id = 213, BankQuestionId = 54, AnswerText = "Đáp án 1 cho câu 54", IsCorrected = true },
            new Answer { Id = 214, BankQuestionId = 54, AnswerText = "Đáp án 2 cho câu 54", IsCorrected = false },
            new Answer { Id = 215, BankQuestionId = 54, AnswerText = "Đáp án 3 cho câu 54", IsCorrected = false },
            new Answer { Id = 216, BankQuestionId = 54, AnswerText = "Đáp án 4 cho câu 54", IsCorrected = false },
            new Answer { Id = 217, BankQuestionId = 55, AnswerText = "Đáp án 1 cho câu 55", IsCorrected = true },
            new Answer { Id = 218, BankQuestionId = 55, AnswerText = "Đáp án 2 cho câu 55", IsCorrected = false },
            new Answer { Id = 219, BankQuestionId = 55, AnswerText = "Đáp án 3 cho câu 55", IsCorrected = false },
            new Answer { Id = 220, BankQuestionId = 55, AnswerText = "Đáp án 4 cho câu 55", IsCorrected = false },
            new Answer { Id = 221, BankQuestionId = 56, AnswerText = "Đáp án 1 cho câu 56", IsCorrected = true },
            new Answer { Id = 222, BankQuestionId = 56, AnswerText = "Đáp án 2 cho câu 56", IsCorrected = false },
            new Answer { Id = 223, BankQuestionId = 56, AnswerText = "Đáp án 3 cho câu 56", IsCorrected = false },
            new Answer { Id = 224, BankQuestionId = 56, AnswerText = "Đáp án 4 cho câu 56", IsCorrected = false },
            new Answer { Id = 225, BankQuestionId = 57, AnswerText = "Đáp án 1 cho câu 57", IsCorrected = true },
            new Answer { Id = 226, BankQuestionId = 57, AnswerText = "Đáp án 2 cho câu 57", IsCorrected = false },
            new Answer { Id = 227, BankQuestionId = 57, AnswerText = "Đáp án 3 cho câu 57", IsCorrected = false },
            new Answer { Id = 228, BankQuestionId = 57, AnswerText = "Đáp án 4 cho câu 57", IsCorrected = false },
            new Answer { Id = 229, BankQuestionId = 58, AnswerText = "Đáp án 1 cho câu 58", IsCorrected = true },
            new Answer { Id = 230, BankQuestionId = 58, AnswerText = "Đáp án 2 cho câu 58", IsCorrected = false },
            new Answer { Id = 231, BankQuestionId = 58, AnswerText = "Đáp án 3 cho câu 58", IsCorrected = false },
            new Answer { Id = 232, BankQuestionId = 58, AnswerText = "Đáp án 4 cho câu 58", IsCorrected = false },
            new Answer { Id = 233, BankQuestionId = 59, AnswerText = "Đáp án 1 cho câu 59", IsCorrected = true },
            new Answer { Id = 234, BankQuestionId = 59, AnswerText = "Đáp án 2 cho câu 59", IsCorrected = false },
            new Answer { Id = 235, BankQuestionId = 59, AnswerText = "Đáp án 3 cho câu 59", IsCorrected = false },
            new Answer { Id = 236, BankQuestionId = 59, AnswerText = "Đáp án 4 cho câu 59", IsCorrected = false },
            new Answer { Id = 237, BankQuestionId = 60, AnswerText = "Đáp án 1 cho câu 60", IsCorrected = true },
            new Answer { Id = 238, BankQuestionId = 60, AnswerText = "Đáp án 2 cho câu 60", IsCorrected = false },
            new Answer { Id = 239, BankQuestionId = 60, AnswerText = "Đáp án 3 cho câu 60", IsCorrected = false },
            new Answer { Id = 240, BankQuestionId = 60, AnswerText = "Đáp án 4 cho câu 60", IsCorrected = false },
            new Answer { Id = 241, BankQuestionId = 61, AnswerText = "Đáp án 1 cho câu 61", IsCorrected = true },
            new Answer { Id = 242, BankQuestionId = 61, AnswerText = "Đáp án 2 cho câu 61", IsCorrected = false },
            new Answer { Id = 243, BankQuestionId = 61, AnswerText = "Đáp án 3 cho câu 61", IsCorrected = false },
            new Answer { Id = 244, BankQuestionId = 61, AnswerText = "Đáp án 4 cho câu 61", IsCorrected = false },
            new Answer { Id = 245, BankQuestionId = 62, AnswerText = "Đáp án 1 cho câu 62", IsCorrected = true },
            new Answer { Id = 246, BankQuestionId = 62, AnswerText = "Đáp án 2 cho câu 62", IsCorrected = false },
            new Answer { Id = 247, BankQuestionId = 62, AnswerText = "Đáp án 3 cho câu 62", IsCorrected = false },
            new Answer { Id = 248, BankQuestionId = 62, AnswerText = "Đáp án 4 cho câu 62", IsCorrected = false },
            new Answer { Id = 249, BankQuestionId = 63, AnswerText = "Đáp án 1 cho câu 63", IsCorrected = true },
            new Answer { Id = 250, BankQuestionId = 63, AnswerText = "Đáp án 2 cho câu 63", IsCorrected = false },
            new Answer { Id = 251, BankQuestionId = 63, AnswerText = "Đáp án 3 cho câu 63", IsCorrected = false },
            new Answer { Id = 252, BankQuestionId = 63, AnswerText = "Đáp án 4 cho câu 63", IsCorrected = false },
            new Answer { Id = 253, BankQuestionId = 64, AnswerText = "Đáp án 1 cho câu 64", IsCorrected = true },
            new Answer { Id = 254, BankQuestionId = 64, AnswerText = "Đáp án 2 cho câu 64", IsCorrected = false },
            new Answer { Id = 255, BankQuestionId = 64, AnswerText = "Đáp án 3 cho câu 64", IsCorrected = false },
            new Answer { Id = 256, BankQuestionId = 64, AnswerText = "Đáp án 4 cho câu 64", IsCorrected = false },
            new Answer { Id = 257, BankQuestionId = 65, AnswerText = "Đáp án 1 cho câu 65", IsCorrected = true },
            new Answer { Id = 258, BankQuestionId = 65, AnswerText = "Đáp án 2 cho câu 65", IsCorrected = false },
            new Answer { Id = 259, BankQuestionId = 65, AnswerText = "Đáp án 3 cho câu 65", IsCorrected = false },
            new Answer { Id = 260, BankQuestionId = 65, AnswerText = "Đáp án 4 cho câu 65", IsCorrected = false },
            new Answer { Id = 261, BankQuestionId = 66, AnswerText = "Đáp án 1 cho câu 66", IsCorrected = true },
            new Answer { Id = 262, BankQuestionId = 66, AnswerText = "Đáp án 2 cho câu 66", IsCorrected = false },
            new Answer { Id = 263, BankQuestionId = 66, AnswerText = "Đáp án 3 cho câu 66", IsCorrected = false },
            new Answer { Id = 264, BankQuestionId = 66, AnswerText = "Đáp án 4 cho câu 66", IsCorrected = false },
            new Answer { Id = 265, BankQuestionId = 67, AnswerText = "Đáp án 1 cho câu 67", IsCorrected = true },
            new Answer { Id = 266, BankQuestionId = 67, AnswerText = "Đáp án 2 cho câu 67", IsCorrected = false },
            new Answer { Id = 267, BankQuestionId = 67, AnswerText = "Đáp án 3 cho câu 67", IsCorrected = false },
            new Answer { Id = 268, BankQuestionId = 67, AnswerText = "Đáp án 4 cho câu 67", IsCorrected = false },
            new Answer { Id = 269, BankQuestionId = 68, AnswerText = "Đáp án 1 cho câu 68", IsCorrected = true },
            new Answer { Id = 270, BankQuestionId = 68, AnswerText = "Đáp án 2 cho câu 68", IsCorrected = false },
            new Answer { Id = 271, BankQuestionId = 68, AnswerText = "Đáp án 3 cho câu 68", IsCorrected = false },
            new Answer { Id = 272, BankQuestionId = 68, AnswerText = "Đáp án 4 cho câu 68", IsCorrected = false },
            new Answer { Id = 273, BankQuestionId = 69, AnswerText = "Đáp án 1 cho câu 69", IsCorrected = true },
            new Answer { Id = 274, BankQuestionId = 69, AnswerText = "Đáp án 2 cho câu 69", IsCorrected = false },
            new Answer { Id = 275, BankQuestionId = 69, AnswerText = "Đáp án 3 cho câu 69", IsCorrected = false },
            new Answer { Id = 276, BankQuestionId = 69, AnswerText = "Đáp án 4 cho câu 69", IsCorrected = false },
            new Answer { Id = 277, BankQuestionId = 70, AnswerText = "Đáp án 1 cho câu 70", IsCorrected = true },
            new Answer { Id = 278, BankQuestionId = 70, AnswerText = "Đáp án 2 cho câu 70", IsCorrected = false },
            new Answer { Id = 279, BankQuestionId = 70, AnswerText = "Đáp án 3 cho câu 70", IsCorrected = false },
            new Answer { Id = 280, BankQuestionId = 70, AnswerText = "Đáp án 4 cho câu 70", IsCorrected = false },
            new Answer { Id = 281, BankQuestionId = 71, AnswerText = "Đáp án 1 cho câu 71", IsCorrected = true },
            new Answer { Id = 282, BankQuestionId = 71, AnswerText = "Đáp án 2 cho câu 71", IsCorrected = false },
            new Answer { Id = 283, BankQuestionId = 71, AnswerText = "Đáp án 3 cho câu 71", IsCorrected = false },
            new Answer { Id = 284, BankQuestionId = 71, AnswerText = "Đáp án 4 cho câu 71", IsCorrected = false },
            new Answer { Id = 285, BankQuestionId = 72, AnswerText = "Đáp án 1 cho câu 72", IsCorrected = true },
            new Answer { Id = 286, BankQuestionId = 72, AnswerText = "Đáp án 2 cho câu 72", IsCorrected = false },
            new Answer { Id = 287, BankQuestionId = 72, AnswerText = "Đáp án 3 cho câu 72", IsCorrected = false },
            new Answer { Id = 288, BankQuestionId = 72, AnswerText = "Đáp án 4 cho câu 72", IsCorrected = false },
            new Answer { Id = 289, BankQuestionId = 73, AnswerText = "Đáp án 1 cho câu 73", IsCorrected = true },
            new Answer { Id = 290, BankQuestionId = 73, AnswerText = "Đáp án 2 cho câu 73", IsCorrected = false },
            new Answer { Id = 291, BankQuestionId = 73, AnswerText = "Đáp án 3 cho câu 73", IsCorrected = false },
            new Answer { Id = 292, BankQuestionId = 73, AnswerText = "Đáp án 4 cho câu 73", IsCorrected = false },
            new Answer { Id = 293, BankQuestionId = 74, AnswerText = "Đáp án 1 cho câu 74", IsCorrected = true },
            new Answer { Id = 294, BankQuestionId = 74, AnswerText = "Đáp án 2 cho câu 74", IsCorrected = false },
            new Answer { Id = 295, BankQuestionId = 74, AnswerText = "Đáp án 3 cho câu 74", IsCorrected = false },
            new Answer { Id = 296, BankQuestionId = 74, AnswerText = "Đáp án 4 cho câu 74", IsCorrected = false },
            new Answer { Id = 297, BankQuestionId = 75, AnswerText = "Đáp án 1 cho câu 75", IsCorrected = true },
            new Answer { Id = 298, BankQuestionId = 75, AnswerText = "Đáp án 2 cho câu 75", IsCorrected = false },
            new Answer { Id = 299, BankQuestionId = 75, AnswerText = "Đáp án 3 cho câu 75", IsCorrected = false },
            new Answer { Id = 300, BankQuestionId = 75, AnswerText = "Đáp án 4 cho câu 75", IsCorrected = false },
            new Answer { Id = 301, BankQuestionId = 76, AnswerText = "Đáp án 1 cho câu 76", IsCorrected = true },
            new Answer { Id = 302, BankQuestionId = 76, AnswerText = "Đáp án 2 cho câu 76", IsCorrected = false },
            new Answer { Id = 303, BankQuestionId = 76, AnswerText = "Đáp án 3 cho câu 76", IsCorrected = false },
            new Answer { Id = 304, BankQuestionId = 76, AnswerText = "Đáp án 4 cho câu 76", IsCorrected = false },
            new Answer { Id = 305, BankQuestionId = 77, AnswerText = "Đáp án 1 cho câu 77", IsCorrected = true },
            new Answer { Id = 306, BankQuestionId = 77, AnswerText = "Đáp án 2 cho câu 77", IsCorrected = false },
            new Answer { Id = 307, BankQuestionId = 77, AnswerText = "Đáp án 3 cho câu 77", IsCorrected = false },
            new Answer { Id = 308, BankQuestionId = 77, AnswerText = "Đáp án 4 cho câu 77", IsCorrected = false },
            new Answer { Id = 309, BankQuestionId = 78, AnswerText = "Đáp án 1 cho câu 78", IsCorrected = true },
            new Answer { Id = 310, BankQuestionId = 78, AnswerText = "Đáp án 2 cho câu 78", IsCorrected = false },
            new Answer { Id = 311, BankQuestionId = 78, AnswerText = "Đáp án 3 cho câu 78", IsCorrected = false },
            new Answer { Id = 312, BankQuestionId = 78, AnswerText = "Đáp án 4 cho câu 78", IsCorrected = false },
            new Answer { Id = 313, BankQuestionId = 79, AnswerText = "Đáp án 1 cho câu 79", IsCorrected = true },
            new Answer { Id = 314, BankQuestionId = 79, AnswerText = "Đáp án 2 cho câu 79", IsCorrected = false },
            new Answer { Id = 315, BankQuestionId = 79, AnswerText = "Đáp án 3 cho câu 79", IsCorrected = false },
            new Answer { Id = 316, BankQuestionId = 79, AnswerText = "Đáp án 4 cho câu 79", IsCorrected = false },
            new Answer { Id = 317, BankQuestionId = 80, AnswerText = "Đáp án 1 cho câu 80", IsCorrected = true },
            new Answer { Id = 318, BankQuestionId = 80, AnswerText = "Đáp án 2 cho câu 80", IsCorrected = false },
            new Answer { Id = 319, BankQuestionId = 80, AnswerText = "Đáp án 3 cho câu 80", IsCorrected = false },
            new Answer { Id = 320, BankQuestionId = 80, AnswerText = "Đáp án 4 cho câu 80", IsCorrected = false },
            new Answer { Id = 321, BankQuestionId = 81, AnswerText = "Đáp án 1 cho câu 81", IsCorrected = true },
            new Answer { Id = 322, BankQuestionId = 81, AnswerText = "Đáp án 2 cho câu 81", IsCorrected = false },
            new Answer { Id = 323, BankQuestionId = 81, AnswerText = "Đáp án 3 cho câu 81", IsCorrected = false },
            new Answer { Id = 324, BankQuestionId = 81, AnswerText = "Đáp án 4 cho câu 81", IsCorrected = false },
            new Answer { Id = 325, BankQuestionId = 82, AnswerText = "Đáp án 1 cho câu 82", IsCorrected = true },
            new Answer { Id = 326, BankQuestionId = 82, AnswerText = "Đáp án 2 cho câu 82", IsCorrected = false },
            new Answer { Id = 327, BankQuestionId = 82, AnswerText = "Đáp án 3 cho câu 82", IsCorrected = false },
            new Answer { Id = 328, BankQuestionId = 82, AnswerText = "Đáp án 4 cho câu 82", IsCorrected = false },
            new Answer { Id = 329, BankQuestionId = 83, AnswerText = "Đáp án 1 cho câu 83", IsCorrected = true },
            new Answer { Id = 330, BankQuestionId = 83, AnswerText = "Đáp án 2 cho câu 83", IsCorrected = false },
            new Answer { Id = 331, BankQuestionId = 83, AnswerText = "Đáp án 3 cho câu 83", IsCorrected = false },
            new Answer { Id = 332, BankQuestionId = 83, AnswerText = "Đáp án 4 cho câu 83", IsCorrected = false },
            new Answer { Id = 333, BankQuestionId = 84, AnswerText = "Đáp án 1 cho câu 84", IsCorrected = true },
            new Answer { Id = 334, BankQuestionId = 84, AnswerText = "Đáp án 2 cho câu 84", IsCorrected = false },
            new Answer { Id = 335, BankQuestionId = 84, AnswerText = "Đáp án 3 cho câu 84", IsCorrected = false },
            new Answer { Id = 336, BankQuestionId = 84, AnswerText = "Đáp án 4 cho câu 84", IsCorrected = false },
            new Answer { Id = 337, BankQuestionId = 85, AnswerText = "Đáp án 1 cho câu 85", IsCorrected = true },
            new Answer { Id = 338, BankQuestionId = 85, AnswerText = "Đáp án 2 cho câu 85", IsCorrected = false },
            new Answer { Id = 339, BankQuestionId = 85, AnswerText = "Đáp án 3 cho câu 85", IsCorrected = false },
            new Answer { Id = 340, BankQuestionId = 85, AnswerText = "Đáp án 4 cho câu 85", IsCorrected = false },
            new Answer { Id = 341, BankQuestionId = 86, AnswerText = "Đáp án 1 cho câu 86", IsCorrected = true },
            new Answer { Id = 342, BankQuestionId = 86, AnswerText = "Đáp án 2 cho câu 86", IsCorrected = false },
            new Answer { Id = 343, BankQuestionId = 86, AnswerText = "Đáp án 3 cho câu 86", IsCorrected = false },
            new Answer { Id = 344, BankQuestionId = 86, AnswerText = "Đáp án 4 cho câu 86", IsCorrected = false },
            new Answer { Id = 345, BankQuestionId = 87, AnswerText = "Đáp án 1 cho câu 87", IsCorrected = true },
            new Answer { Id = 346, BankQuestionId = 87, AnswerText = "Đáp án 2 cho câu 87", IsCorrected = false },
            new Answer { Id = 347, BankQuestionId = 87, AnswerText = "Đáp án 3 cho câu 87", IsCorrected = false },
            new Answer { Id = 348, BankQuestionId = 87, AnswerText = "Đáp án 4 cho câu 87", IsCorrected = false },
            new Answer { Id = 349, BankQuestionId = 88, AnswerText = "Đáp án 1 cho câu 88", IsCorrected = true },
            new Answer { Id = 350, BankQuestionId = 88, AnswerText = "Đáp án 2 cho câu 88", IsCorrected = false },
            new Answer { Id = 351, BankQuestionId = 88, AnswerText = "Đáp án 3 cho câu 88", IsCorrected = false },
            new Answer { Id = 352, BankQuestionId = 88, AnswerText = "Đáp án 4 cho câu 88", IsCorrected = false },
            new Answer { Id = 353, BankQuestionId = 89, AnswerText = "Đáp án 1 cho câu 89", IsCorrected = true },
            new Answer { Id = 354, BankQuestionId = 89, AnswerText = "Đáp án 2 cho câu 89", IsCorrected = false },
            new Answer { Id = 355, BankQuestionId = 89, AnswerText = "Đáp án 3 cho câu 89", IsCorrected = false },
            new Answer { Id = 356, BankQuestionId = 89, AnswerText = "Đáp án 4 cho câu 89", IsCorrected = false },
            new Answer { Id = 357, BankQuestionId = 90, AnswerText = "Đáp án 1 cho câu 90", IsCorrected = true },
            new Answer { Id = 358, BankQuestionId = 90, AnswerText = "Đáp án 2 cho câu 90", IsCorrected = false },
            new Answer { Id = 359, BankQuestionId = 90, AnswerText = "Đáp án 3 cho câu 90", IsCorrected = false },
            new Answer { Id = 360, BankQuestionId = 90, AnswerText = "Đáp án 4 cho câu 90", IsCorrected = false },
            new Answer { Id = 361, BankQuestionId = 91, AnswerText = "Đáp án 1 cho câu 91", IsCorrected = true },
            new Answer { Id = 362, BankQuestionId = 91, AnswerText = "Đáp án 2 cho câu 91", IsCorrected = false },
            new Answer { Id = 363, BankQuestionId = 91, AnswerText = "Đáp án 3 cho câu 91", IsCorrected = false },
            new Answer { Id = 364, BankQuestionId = 91, AnswerText = "Đáp án 4 cho câu 91", IsCorrected = false },
            new Answer { Id = 365, BankQuestionId = 92, AnswerText = "Đáp án 1 cho câu 92", IsCorrected = true },
            new Answer { Id = 366, BankQuestionId = 92, AnswerText = "Đáp án 2 cho câu 92", IsCorrected = false },
            new Answer { Id = 367, BankQuestionId = 92, AnswerText = "Đáp án 3 cho câu 92", IsCorrected = false },
            new Answer { Id = 368, BankQuestionId = 92, AnswerText = "Đáp án 4 cho câu 92", IsCorrected = false },
            new Answer { Id = 369, BankQuestionId = 93, AnswerText = "Đáp án 1 cho câu 93", IsCorrected = true },
            new Answer { Id = 370, BankQuestionId = 93, AnswerText = "Đáp án 2 cho câu 93", IsCorrected = false },
            new Answer { Id = 371, BankQuestionId = 93, AnswerText = "Đáp án 3 cho câu 93", IsCorrected = false },
            new Answer { Id = 372, BankQuestionId = 93, AnswerText = "Đáp án 4 cho câu 93", IsCorrected = false },
            new Answer { Id = 373, BankQuestionId = 94, AnswerText = "Đáp án 1 cho câu 94", IsCorrected = true },
            new Answer { Id = 374, BankQuestionId = 94, AnswerText = "Đáp án 2 cho câu 94", IsCorrected = false },
            new Answer { Id = 375, BankQuestionId = 94, AnswerText = "Đáp án 3 cho câu 94", IsCorrected = false },
            new Answer { Id = 376, BankQuestionId = 94, AnswerText = "Đáp án 4 cho câu 94", IsCorrected = false },
            new Answer { Id = 377, BankQuestionId = 95, AnswerText = "Đáp án 1 cho câu 95", IsCorrected = true },
            new Answer { Id = 378, BankQuestionId = 95, AnswerText = "Đáp án 2 cho câu 95", IsCorrected = false },
            new Answer { Id = 379, BankQuestionId = 95, AnswerText = "Đáp án 3 cho câu 95", IsCorrected = false },
            new Answer { Id = 380, BankQuestionId = 95, AnswerText = "Đáp án 4 cho câu 95", IsCorrected = false },
            new Answer { Id = 381, BankQuestionId = 96, AnswerText = "Đáp án 1 cho câu 96", IsCorrected = true },
            new Answer { Id = 382, BankQuestionId = 96, AnswerText = "Đáp án 2 cho câu 96", IsCorrected = false },
            new Answer { Id = 383, BankQuestionId = 96, AnswerText = "Đáp án 3 cho câu 96", IsCorrected = false },
            new Answer { Id = 384, BankQuestionId = 96, AnswerText = "Đáp án 4 cho câu 96", IsCorrected = false },
            new Answer { Id = 385, BankQuestionId = 97, AnswerText = "Đáp án 1 cho câu 97", IsCorrected = true },
            new Answer { Id = 386, BankQuestionId = 97, AnswerText = "Đáp án 2 cho câu 97", IsCorrected = false },
            new Answer { Id = 387, BankQuestionId = 97, AnswerText = "Đáp án 3 cho câu 97", IsCorrected = false },
            new Answer { Id = 388, BankQuestionId = 97, AnswerText = "Đáp án 4 cho câu 97", IsCorrected = false },
            new Answer { Id = 389, BankQuestionId = 98, AnswerText = "Đáp án 1 cho câu 98", IsCorrected = true },
            new Answer { Id = 390, BankQuestionId = 98, AnswerText = "Đáp án 2 cho câu 98", IsCorrected = false },
            new Answer { Id = 391, BankQuestionId = 98, AnswerText = "Đáp án 3 cho câu 98", IsCorrected = false },
            new Answer { Id = 392, BankQuestionId = 98, AnswerText = "Đáp án 4 cho câu 98", IsCorrected = false },
            new Answer { Id = 393, BankQuestionId = 99, AnswerText = "Đáp án 1 cho câu 99", IsCorrected = true },
            new Answer { Id = 394, BankQuestionId = 99, AnswerText = "Đáp án 2 cho câu 99", IsCorrected = false },
            new Answer { Id = 395, BankQuestionId = 99, AnswerText = "Đáp án 3 cho câu 99", IsCorrected = false },
            new Answer { Id = 396, BankQuestionId = 99, AnswerText = "Đáp án 4 cho câu 99", IsCorrected = false },
            new Answer { Id = 397, BankQuestionId = 100, AnswerText = "Đáp án 1 cho câu 100", IsCorrected = true },
            new Answer { Id = 398, BankQuestionId = 100, AnswerText = "Đáp án 2 cho câu 100", IsCorrected = false },
            new Answer { Id = 399, BankQuestionId = 100, AnswerText = "Đáp án 3 cho câu 100", IsCorrected = false },
            new Answer { Id = 400, BankQuestionId = 100, AnswerText = "Đáp án 4 cho câu 100", IsCorrected = false }
            );
            modelBuilder.Entity<Exam>(entity =>
            {
                List<Exam> exams = new List<Exam>
                {
                    new Exam
                    {
                        Id = 1,
                        PremiumUserId = null,
                        SubjectId = 1,
                        SourceText = "Tổng hợp 12 nội dung môn Triết học",
                        TotalQuestion = 50,
                        IsPublic = true,
                        Title = "Đề thi Triết học - Phần 1",
                        Description = "Các câu hỏi thuộc nội dung: Vật chất & Ý thức, Lượng – Chất, Phép biện chứng",
                        CreatedAt = DateTime.Now,
                        TotalTime = TimeSpan.FromSeconds(10)},
                    new Exam
                           {
                               Id = 2,
                               Title = "Đề thi Triết học - Phần 2",
                               Description = "Các câu hỏi thuộc nội dung: Con người, Nhận thức, Thực tiễn, Chủ nghĩa xã hội",
                               SourceText = "Tổng hợp 12 nội dung môn Triết học",
                               SubjectId = 1,
                               TotalQuestion = 50,
                               IsPublic = true,
                               CreatedAt = DateTime.Now,
							   TotalTime = TimeSpan.FromSeconds(10)
						   }
                 };
                entity.HasData(exams);
            });
            modelBuilder.Entity<QuestionExam>().HasData(
            new QuestionExam { Id = 1, ExamId = 1, BankQuestionId = 1, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 1: Chủ nghĩa duy vật biện chứng - Nội dung trọng tâm số 1" },
            new QuestionExam { Id = 2, ExamId = 1, BankQuestionId = 2, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 2: Chủ nghĩa duy vật biện chứng - Nội dung trọng tâm số 2" },
            new QuestionExam { Id = 3, ExamId = 1, BankQuestionId = 3, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 3: Chủ nghĩa duy vật biện chứng - Nội dung trọng tâm số 3" },
            new QuestionExam { Id = 4, ExamId = 1, BankQuestionId = 4, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 4: Chủ nghĩa duy vật biện chứng - Nội dung trọng tâm số 4" },
            new QuestionExam { Id = 5, ExamId = 1, BankQuestionId = 5, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 5: Chủ nghĩa duy vật biện chứng - Nội dung trọng tâm số 5" },
            new QuestionExam { Id = 6, ExamId = 1, BankQuestionId = 6, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 6: Chủ nghĩa duy vật biện chứng - Nội dung trọng tâm số 6" },
            new QuestionExam { Id = 7, ExamId = 1, BankQuestionId = 7, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 7: Chủ nghĩa duy vật biện chứng - Nội dung trọng tâm số 7" },
            new QuestionExam { Id = 8, ExamId = 1, BankQuestionId = 8, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 8: Chủ nghĩa duy vật biện chứng - Nội dung trọng tâm số 8" },
            new QuestionExam { Id = 9, ExamId = 1, BankQuestionId = 9, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 9: Chủ nghĩa duy vật biện chứng - Nội dung trọng tâm số 9" },
            new QuestionExam { Id = 10, ExamId = 1, BankQuestionId = 10, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 10: Phép biện chứng - Nội dung trọng tâm số 10" },
            new QuestionExam { Id = 11, ExamId = 1, BankQuestionId = 11, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 11: Phép biện chứng - Nội dung trọng tâm số 11" },
            new QuestionExam { Id = 12, ExamId = 1, BankQuestionId = 12, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 12: Phép biện chứng - Nội dung trọng tâm số 12" },
            new QuestionExam { Id = 13, ExamId = 1, BankQuestionId = 13, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 13: Phép biện chứng - Nội dung trọng tâm số 13" },
            new QuestionExam { Id = 14, ExamId = 1, BankQuestionId = 14, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 14: Phép biện chứng - Nội dung trọng tâm số 14" },
            new QuestionExam { Id = 15, ExamId = 1, BankQuestionId = 15, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 15: Phép biện chứng - Nội dung trọng tâm số 15" },
            new QuestionExam { Id = 16, ExamId = 1, BankQuestionId = 16, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 16: Phép biện chứng - Nội dung trọng tâm số 16" },
            new QuestionExam { Id = 17, ExamId = 1, BankQuestionId = 17, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 17: Phép biện chứng - Nội dung trọng tâm số 17" },
            new QuestionExam { Id = 18, ExamId = 1, BankQuestionId = 18, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 18: Phép biện chứng - Nội dung trọng tâm số 18" },
            new QuestionExam { Id = 19, ExamId = 1, BankQuestionId = 19, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 19: Vật chất và ý thức - Nội dung trọng tâm số 19" },
            new QuestionExam { Id = 20, ExamId = 1, BankQuestionId = 20, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 20: Vật chất và ý thức - Nội dung trọng tâm số 20" },
            new QuestionExam { Id = 21, ExamId = 1, BankQuestionId = 21, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 21: Vật chất và ý thức - Nội dung trọng tâm số 21" },
            new QuestionExam { Id = 22, ExamId = 1, BankQuestionId = 22, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 22: Vật chất và ý thức - Nội dung trọng tâm số 22" },
            new QuestionExam { Id = 23, ExamId = 1, BankQuestionId = 23, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 23: Vật chất và ý thức - Nội dung trọng tâm số 23" },
            new QuestionExam { Id = 24, ExamId = 1, BankQuestionId = 24, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 24: Vật chất và ý thức - Nội dung trọng tâm số 24" },
            new QuestionExam { Id = 25, ExamId = 1, BankQuestionId = 25, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 25: Vật chất và ý thức - Nội dung trọng tâm số 25" },
            new QuestionExam { Id = 26, ExamId = 1, BankQuestionId = 26, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 26: Vật chất và ý thức - Nội dung trọng tâm số 26" },
            new QuestionExam { Id = 27, ExamId = 1, BankQuestionId = 27, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 27: Vật chất và ý thức - Nội dung trọng tâm số 27" },
            new QuestionExam { Id = 28, ExamId = 1, BankQuestionId = 28, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 28: Phép biện chứng về lượng và chất - Nội dung trọng tâm số 28" },
            new QuestionExam { Id = 29, ExamId = 1, BankQuestionId = 29, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 29: Phép biện chứng về lượng và chất - Nội dung trọng tâm số 29" },
            new QuestionExam { Id = 30, ExamId = 1, BankQuestionId = 30, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 30: Phép biện chứng về lượng và chất - Nội dung trọng tâm số 30" },
            new QuestionExam { Id = 31, ExamId = 1, BankQuestionId = 31, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 31: Phép biện chứng về lượng và chất - Nội dung trọng tâm số 31" },
            new QuestionExam { Id = 32, ExamId = 1, BankQuestionId = 32, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 32: Phép biện chứng về lượng và chất - Nội dung trọng tâm số 32" },
            new QuestionExam { Id = 33, ExamId = 1, BankQuestionId = 33, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 33: Phép biện chứng về lượng và chất - Nội dung trọng tâm số 33" },
            new QuestionExam { Id = 34, ExamId = 1, BankQuestionId = 34, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 34: Phép biện chứng về lượng và chất - Nội dung trọng tâm số 34" },
            new QuestionExam { Id = 35, ExamId = 1, BankQuestionId = 35, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 35: Phép biện chứng về lượng và chất - Nội dung trọng tâm số 35" },
            new QuestionExam { Id = 36, ExamId = 1, BankQuestionId = 36, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 36: Phép biện chứng về lượng và chất - Nội dung trọng tâm số 36" },
            new QuestionExam { Id = 37, ExamId = 1, BankQuestionId = 37, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 37: Nguyên lý về mâu thuẫn - Nội dung trọng tâm số 37" },
            new QuestionExam { Id = 38, ExamId = 1, BankQuestionId = 38, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 38: Nguyên lý về mâu thuẫn - Nội dung trọng tâm số 38" },
            new QuestionExam { Id = 39, ExamId = 1, BankQuestionId = 39, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 39: Nguyên lý về mâu thuẫn - Nội dung trọng tâm số 39" },
            new QuestionExam { Id = 40, ExamId = 1, BankQuestionId = 40, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 40: Nguyên lý về mâu thuẫn - Nội dung trọng tâm số 40" },
            new QuestionExam { Id = 41, ExamId = 1, BankQuestionId = 41, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 41: Nguyên lý về mâu thuẫn - Nội dung trọng tâm số 41" },
            new QuestionExam { Id = 42, ExamId = 1, BankQuestionId = 42, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 42: Nguyên lý về mâu thuẫn - Nội dung trọng tâm số 42" },
            new QuestionExam { Id = 43, ExamId = 1, BankQuestionId = 43, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 43: Nguyên lý về mâu thuẫn - Nội dung trọng tâm số 43" },
            new QuestionExam { Id = 44, ExamId = 1, BankQuestionId = 44, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 44: Nguyên lý về mâu thuẫn - Nội dung trọng tâm số 44" },
            new QuestionExam { Id = 45, ExamId = 1, BankQuestionId = 45, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 45: Nguyên lý về mâu thuẫn - Nội dung trọng tâm số 45" },
            new QuestionExam { Id = 46, ExamId = 1, BankQuestionId = 46, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 46: Nhận thức và thực tiễn - Nội dung trọng tâm số 46" },
            new QuestionExam { Id = 47, ExamId = 1, BankQuestionId = 47, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 47: Nhận thức và thực tiễn - Nội dung trọng tâm số 47" },
            new QuestionExam { Id = 48, ExamId = 1, BankQuestionId = 48, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 48: Nhận thức và thực tiễn - Nội dung trọng tâm số 48" },
            new QuestionExam { Id = 49, ExamId = 1, BankQuestionId = 49, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 49: Nhận thức và thực tiễn - Nội dung trọng tâm số 49" },
            new QuestionExam { Id = 50, ExamId = 1, BankQuestionId = 50, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 50: Nhận thức và thực tiễn - Nội dung trọng tâm số 50" },
            new QuestionExam { Id = 51, ExamId = 2, BankQuestionId = 51, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 51: Nhận thức và thực tiễn - Nội dung trọng tâm số 1" },
            new QuestionExam { Id = 52, ExamId = 2, BankQuestionId = 52, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 52: Nhận thức và thực tiễn - Nội dung trọng tâm số 2" },
            new QuestionExam { Id = 53, ExamId = 2, BankQuestionId = 53, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 53: Nhận thức và thực tiễn - Nội dung trọng tâm số 3" },
            new QuestionExam { Id = 54, ExamId = 2, BankQuestionId = 54, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 54: Nhận thức và thực tiễn - Nội dung trọng tâm số 4" },
            new QuestionExam { Id = 55, ExamId = 2, BankQuestionId = 55, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 55: Vai trò của con người - Nội dung trọng tâm số 5" },
            new QuestionExam { Id = 56, ExamId = 2, BankQuestionId = 56, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 56: Vai trò của con người - Nội dung trọng tâm số 6" },
            new QuestionExam { Id = 57, ExamId = 2, BankQuestionId = 57, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 57: Vai trò của con người - Nội dung trọng tâm số 7" },
            new QuestionExam { Id = 58, ExamId = 2, BankQuestionId = 58, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 58: Vai trò của con người - Nội dung trọng tâm số 8" },
            new QuestionExam { Id = 59, ExamId = 2, BankQuestionId = 59, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 59: Vai trò của con người - Nội dung trọng tâm số 9" },
            new QuestionExam { Id = 60, ExamId = 2, BankQuestionId = 60, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 60: Vai trò của con người - Nội dung trọng tâm số 10" },
            new QuestionExam { Id = 61, ExamId = 2, BankQuestionId = 61, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 61: Vai trò của con người - Nội dung trọng tâm số 11" },
            new QuestionExam { Id = 62, ExamId = 2, BankQuestionId = 62, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 62: Vai trò của con người - Nội dung trọng tâm số 12" },
            new QuestionExam { Id = 63, ExamId = 2, BankQuestionId = 63, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 63: Vai trò của con người - Nội dung trọng tâm số 13" },
            new QuestionExam { Id = 64, ExamId = 2, BankQuestionId = 64, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 64: Chủ nghĩa duy vật lịch sử - Nội dung trọng tâm số 14" },
            new QuestionExam { Id = 65, ExamId = 2, BankQuestionId = 65, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 65: Chủ nghĩa duy vật lịch sử - Nội dung trọng tâm số 15" },
            new QuestionExam { Id = 66, ExamId = 2, BankQuestionId = 66, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 66: Chủ nghĩa duy vật lịch sử - Nội dung trọng tâm số 16" },
            new QuestionExam { Id = 67, ExamId = 2, BankQuestionId = 67, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 67: Chủ nghĩa duy vật lịch sử - Nội dung trọng tâm số 17" },
            new QuestionExam { Id = 68, ExamId = 2, BankQuestionId = 68, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 68: Chủ nghĩa duy vật lịch sử - Nội dung trọng tâm số 18" },
            new QuestionExam { Id = 69, ExamId = 2, BankQuestionId = 69, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 69: Chủ nghĩa duy vật lịch sử - Nội dung trọng tâm số 19" },
            new QuestionExam { Id = 70, ExamId = 2, BankQuestionId = 70, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 70: Chủ nghĩa duy vật lịch sử - Nội dung trọng tâm số 20" },
            new QuestionExam { Id = 71, ExamId = 2, BankQuestionId = 71, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 71: Chủ nghĩa duy vật lịch sử - Nội dung trọng tâm số 21" },
            new QuestionExam { Id = 72, ExamId = 2, BankQuestionId = 72, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 72: Chủ nghĩa duy vật lịch sử - Nội dung trọng tâm số 22" },
            new QuestionExam { Id = 73, ExamId = 2, BankQuestionId = 73, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 73: Hình thái kinh tế xã hội - Nội dung trọng tâm số 23" },
            new QuestionExam { Id = 74, ExamId = 2, BankQuestionId = 74, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 74: Hình thái kinh tế xã hội - Nội dung trọng tâm số 24" },
            new QuestionExam { Id = 75, ExamId = 2, BankQuestionId = 75, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 75: Hình thái kinh tế xã hội - Nội dung trọng tâm số 25" },
            new QuestionExam { Id = 76, ExamId = 2, BankQuestionId = 76, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 76: Hình thái kinh tế xã hội - Nội dung trọng tâm số 26" },
            new QuestionExam { Id = 77, ExamId = 2, BankQuestionId = 77, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 77: Hình thái kinh tế xã hội - Nội dung trọng tâm số 27" },
            new QuestionExam { Id = 78, ExamId = 2, BankQuestionId = 78, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 78: Hình thái kinh tế xã hội - Nội dung trọng tâm số 28" },
            new QuestionExam { Id = 79, ExamId = 2, BankQuestionId = 79, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 79: Hình thái kinh tế xã hội - Nội dung trọng tâm số 29" },
            new QuestionExam { Id = 80, ExamId = 2, BankQuestionId = 80, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 80: Hình thái kinh tế xã hội - Nội dung trọng tâm số 30" },
            new QuestionExam { Id = 81, ExamId = 2, BankQuestionId = 81, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 81: Hình thái kinh tế xã hội - Nội dung trọng tâm số 31" },
            new QuestionExam { Id = 82, ExamId = 2, BankQuestionId = 82, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 82: Giai cấp và đấu tranh giai cấp - Nội dung trọng tâm số 32" },
            new QuestionExam { Id = 83, ExamId = 2, BankQuestionId = 83, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 83: Giai cấp và đấu tranh giai cấp - Nội dung trọng tâm số 33" },
            new QuestionExam { Id = 84, ExamId = 2, BankQuestionId = 84, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 84: Giai cấp và đấu tranh giai cấp - Nội dung trọng tâm số 34" },
            new QuestionExam { Id = 85, ExamId = 2, BankQuestionId = 85, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 85: Giai cấp và đấu tranh giai cấp - Nội dung trọng tâm số 35" },
            new QuestionExam { Id = 86, ExamId = 2, BankQuestionId = 86, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 86: Giai cấp và đấu tranh giai cấp - Nội dung trọng tâm số 36" },
            new QuestionExam { Id = 87, ExamId = 2, BankQuestionId = 87, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 87: Giai cấp và đấu tranh giai cấp - Nội dung trọng tâm số 37" },
            new QuestionExam { Id = 88, ExamId = 2, BankQuestionId = 88, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 88: Giai cấp và đấu tranh giai cấp - Nội dung trọng tâm số 38" },
            new QuestionExam { Id = 89, ExamId = 2, BankQuestionId = 89, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 89: Giai cấp và đấu tranh giai cấp - Nội dung trọng tâm số 39" },
            new QuestionExam { Id = 90, ExamId = 2, BankQuestionId = 90, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 90: Giai cấp và đấu tranh giai cấp - Nội dung trọng tâm số 40" },
            new QuestionExam { Id = 91, ExamId = 2, BankQuestionId = 91, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 91: Nhà nước và cách mạng - Nội dung trọng tâm số 41" },
            new QuestionExam { Id = 92, ExamId = 2, BankQuestionId = 92, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 92: Nhà nước và cách mạng - Nội dung trọng tâm số 42" },
            new QuestionExam { Id = 93, ExamId = 2, BankQuestionId = 93, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 93: Nhà nước và cách mạng - Nội dung trọng tâm số 43" },
            new QuestionExam { Id = 94, ExamId = 2, BankQuestionId = 94, QuestionTypeId = 1, LevelId = 3, IsPublic = true, Content = "Câu 94: Nhà nước và cách mạng - Nội dung trọng tâm số 44" },
            new QuestionExam { Id = 95, ExamId = 2, BankQuestionId = 95, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 95: Nhà nước và cách mạng - Nội dung trọng tâm số 45" },
            new QuestionExam { Id = 96, ExamId = 2, BankQuestionId = 96, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 96: Nhà nước và cách mạng - Nội dung trọng tâm số 46" },
            new QuestionExam { Id = 97, ExamId = 2, BankQuestionId = 97, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 97: Nhà nước và cách mạng - Nội dung trọng tâm số 47" },
            new QuestionExam { Id = 98, ExamId = 2, BankQuestionId = 98, QuestionTypeId = 1, LevelId = 1, IsPublic = true, Content = "Câu 98: Nhà nước và cách mạng - Nội dung trọng tâm số 48" },
            new QuestionExam { Id = 99, ExamId = 2, BankQuestionId = 99, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 99: Nhà nước và cách mạng - Nội dung trọng tâm số 49" },
            new QuestionExam { Id = 100, ExamId = 2, BankQuestionId = 100, QuestionTypeId = 1, LevelId = 2, IsPublic = true, Content = "Câu 100: Chủ nghĩa xã hội khoa học - Nội dung trọng tâm số 50" }
            );

        }
    }
}
